src/Entity/Excursioncomment.php
<?php

namespace App\Entity;

use App\Repository\ExcursioncommentRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=ExcursioncommentRepository::class)
 */
class Excursioncomment
{
    public function __construct() {
        $this->setCreatedAt(new \DateTime());
        $this->setActif(true);
    }
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message="Ce champ est obligatoire")
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message="Ce champ est obligatoire")
     */
    private $email;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Ce champ est obligatoire")
     */
    private $contenu;

    /**
     *  @ORM\Column(type="boolean")
     * @Assert\NotBlank(message="Ce champ est obligatoire")
     */
    private $actif;

    /**
     * @ORM\Column(type="boolean")
     * @Assert\NotBlank(message="Ce champ est obligatoire")
     */
    private $rgpd;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=Excursion::class, inversedBy="excursioncomments")
     */
    private $excursion;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(?string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(?string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getActif(): ?string
    {
        return $this->actif;
    }

    public function setActif(?string $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    public function getRgpd(): ?string
    {
        return $this->rgpd;
    }

    public function setRgpd(?string $rgpd): self
    {
        $this->rgpd = $rgpd;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getExcursion(): ?Excursion
    {
        return $this->excursion;
    }

    public function setExcursion(?Excursion $excursion): self
    {
        $this->excursion = $excursion;

        return $this;
    }
}

src/Form/ExcursioncommentType.php
<?php

namespace App\Form;

use App\Entity\Excursioncomment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ExcursioncommentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('pseudo')
            ->add('email', EmailType::class)
            ->add('contenu')
            ->add('rgpd', CheckboxType::class, [
                'label' => 'J\'accepte que mes informations soient stockées dans la base de données de Mon Blog pour la gestion des commentaires. J\'ai bien noté qu\'en aucun cas ces données ne seront cédées à des tiers.'
            ])
            ->add('envoyer', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Excursioncomment::class,
        ]);
    }
}

src/Controller/ExcursioncommentController.php
<?php

namespace App\Controller;

use App\Entity\Excursioncomment;
use App\Form\ExcursioncommentType;
use App\Repository\ExcursioncommentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/excursioncomment")
 */
class ExcursioncommentController extends AbstractController
{
    /**
     * @Route("/", name="app_excursioncomment_index", methods={"GET"})
     */
    public function index(ExcursioncommentRepository $excursioncommentRepository): Response
    {
        return $this->render('excursioncomment/index.html.twig', [
            'excursioncomments' => $excursioncommentRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_excursioncomment_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ExcursioncommentRepository $excursioncommentRepository): Response
    {
        $excursioncomment = new Excursioncomment();
        $form = $this->createForm(ExcursioncommentType::class, $excursioncomment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $excursioncommentRepository->add($excursioncomment);
            return $this->redirectToRoute('app_excursioncomment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('excursioncomment/new.html.twig', [
            'excursioncomment' => $excursioncomment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_excursioncomment_show", methods={"GET"})
     */
    public function show(Excursioncomment $excursioncomment): Response
    {
        return $this->render('excursioncomment/show.html.twig', [
            'excursioncomment' => $excursioncomment,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_excursioncomment_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Excursioncomment $excursioncomment, ExcursioncommentRepository $excursioncommentRepository): Response
    {
        $form = $this->createForm(ExcursioncommentType::class, $excursioncomment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $excursioncommentRepository->add($excursioncomment);
            return $this->redirectToRoute('app_excursioncomment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('excursioncomment/edit.html.twig', [
            'excursioncomment' => $excursioncomment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_excursioncomment_delete", methods={"POST"})
     */
    public function delete(Request $request, Excursioncomment $excursioncomment, ExcursioncommentRepository $excursioncommentRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$excursioncomment->getId(), $request->request->get('_token'))) {
            $excursioncommentRepository->remove($excursioncomment);
        }

        return $this->redirectToRoute('app_excursioncomment_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/excursioncomment/_delete_form.html.twig
<form method="post" action="{{ path('app_excursioncomment_delete', {'id': excursioncomment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ excursioncomment.id) }}">
    <button class="btn">Delete</button>
</form>

templates/excursioncomment/_form.html.twig
{{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}

    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/excursioncomment/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Excursioncomment{% endblock %}

{% block body %}
    <h1>Edit Excursioncomment</h1>

    {{ include('excursioncomment/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_excursioncomment_index') }}">back to list</a>

    {{ include('excursioncomment/_delete_form.html.twig') }}
{% endblock %}

templates/excursioncomment/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Excursioncomment index{% endblock %}

{% block body %}
    <h1>Excursioncomment index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Pseudo</th>
                <th>Email</th>
                <th>Contenu</th>
                <th>Actif</th>
                <th>Rgpd</th>
                <th>Created_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for excursioncomment in excursioncomments %}
            <tr>
                <td>{{ excursioncomment.id }}</td>
                <td>{{ excursioncomment.pseudo }}</td>
                <td>{{ excursioncomment.email }}</td>
                <td>{{ excursioncomment.contenu }}</td>
                <td>{{ excursioncomment.actif }}</td>
                <td>{{ excursioncomment.rgpd }}</td>
                <td>{{ excursioncomment.createdAt ? excursioncomment.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_excursioncomment_show', {'id': excursioncomment.id}) }}">show</a>
                    <a href="{{ path('app_excursioncomment_edit', {'id': excursioncomment.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_excursioncomment_new') }}">Create new</a>
{% endblock %}

templates/excursioncomment/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Excursioncomment{% endblock %}

{% block body %}
    <h1>Create new Excursioncomment</h1>

    {{ include('excursioncomment/_form.html.twig') }}

    <a href="{{ path('app_excursioncomment_index') }}">back to list</a>
{% endblock %}

templates/excursioncomment/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Excursioncomment{% endblock %}

{% block body %}
    <h1>Excursioncomment</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ excursioncomment.id }}</td>
            </tr>
            <tr>
                <th>Pseudo</th>
                <td>{{ excursioncomment.pseudo }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ excursioncomment.email }}</td>
            </tr>
            <tr>
                <th>Contenu</th>
                <td>{{ excursioncomment.contenu }}</td>
            </tr>
            <tr>
                <th>Actif</th>
                <td>{{ excursioncomment.actif }}</td>
            </tr>
            <tr>
                <th>Rgpd</th>
                <td>{{ excursioncomment.rgpd }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ excursioncomment.createdAt ? excursioncomment.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_excursioncomment_index') }}">back to list</a>

    <a href="{{ path('app_excursioncomment_edit', {'id': excursioncomment.id}) }}">edit</a>

    {{ include('excursioncomment/_delete_form.html.twig') }}
{% endblock %}